### ISSUE TITLE
[Question] about stream tests - writeStream has no `end` event?

### ISSUE THREAD

**Issue by subdavis** [perry-mitchell/webdav-client#106]
Background: I'm working on a contribution as a workaround to a firefox bug.

While testing my changes, I've run into an issue with `createWriteStream.spec.js`

```javascript
writeStream.on("end", function() {
    // stupid stream needs time to close probably..
    waitOnFile(targetFile).then(resolve, reject);
});
```

I'm having an issue where this end event never gets called, and as far as I can tell, there is no such thing as an `end` event for class `stream.Writable` -- see the docs at https://nodejs.org/api/stream.html

I don't know how this ever worked in the first place, but it seems to me that this event should be changed to `finish`, which I can confirm **is** being called.  Could you give a brief explanation of what's going on in this test?

Thanks for the great library, and sorry if this is a dumb question.

**Comment by perry-mitchell** [comment]
@subdavis `writeStream` [is actually a `PassThru`](https://github.com/perry-mitchell/webdav-client/blob/master/test/specs/createWriteStream.spec.js#L47) stream [under the hood](https://github.com/perry-mitchell/webdav-client/blob/master/source/interface/createStream.js#L26).

This is because WebDAV doesn't create any write stream specifically. `fetch` allows us to give it a read stream that it will use to transfer data to the remote endpoint, and we need to write into that same stream.. so a PassThru stream is used to allow both use cases.

**Comment by subdavis** [comment]
great, thank you!
