### ISSUE TITLE
Propfind Depth Header

### ISSUE THREAD

**Issue by skoschik** [perry-mitchell/webdav-client#130]
First, great library.
One suggestion, I think it would be really helpful to support the 'depth' header for PROPFIND requests.   In particular I'm interested in sending Depth:'Infinity' for my use case.

**Comment by perry-mitchell** [comment]
With regards to your PR, #131, one part is definitely to pass a custom depth but we need to handle the following points:

 * We should validate depth to be a number `>= 1`
 * We should modify the parsing of the `getDirectoryContents` method so that it _recursively_ creates the file structure that's returned

It's important that we handle this recursively as imo it makes little sense to have a tree's depth of files contained on 1 "level". We can, when `depth > 1`, add a `children` array to each directory result and recurse into that. In this regard this issue becomes more complex to implement, but I feel it's the right way to go about handling infinite depth.

We could also consider adding an additional property, `depth`, to each result. Every file and folder could have `depth: n` where `n` is the depth it was fetched at (handled by the recursive function), starting at `1`.

**Comment by skoschik** [comment]
For me it's actually optimal as is, being a flat response.
The WebDAV server's XML response is flat, and I think it's easier to deal with the flat results than a nested result.  I'm not sure how much value there is in creating a nested object from the WebDAV server's response.  Recursion everywhere.
I am syncing data between the client and server and on the client I do a recursive directory read BUT that outputs a flat response which can be easily be compared to the webdav's flat response. 

Would you be willing to entertain the idea of an option to have a nested or flat result?

**Comment by skoschik** [comment]
I opened an [issue](https://github.com/OpenMarshal/npm-WebDAV-Server/issues/48) on npm-WebDAV-servers's git because they haven't supported Depth:Infinity yet.  Although, they seem quite interested in doing so.  


We will need them to support this in order to get tests for this feature.
I'm currently using an Apache ModDAV to test with, since it supports depth:infinity

**Comment by skoschik** [comment]
Depth option of`deep: true` sounds great.

Glad you're okay with the flat return object.  

npm-WebDAV-Server released the update to fix the infinity requests today (version 2.4.3).  So we should be able to implements the appropriate tests after making the changes to the server config.
