### ISSUE TITLE
pipe to client.createWriteStream() doesn't write file to server

### ISSUE THREAD

**Issue by RabbidDog** [perry-mitchell/webdav-client#148]
If I pipe from my ReadStream to the client.createWriteStream() , only a 15kb file is ever created on the server. This is true for any file I tried to stream. I verified that the readstream is emitting data chunks.

let me know what details I need to provide.

**Comment by perry-mitchell** [comment]
Hi,

Please provide a working Gist or other example I can access so that I can reproduce the issue. Obviously without credentials or details regarding your host. The file you’re writing should be small enough to share too.

Better yet would be to create a failing test, but I’ll leave that up to you.

**Comment by perry-mitchell** [comment]
Closing as no test case: [Contribution guide](https://github.com/perry-mitchell/webdav-client/blob/master/CONTRIBUTING.md).
