### ISSUE TITLE
error Network Error

### ISSUE THREAD

**Issue by StefanHos** [perry-mitchell/webdav-client#188]
Hi Guys, 
please can you help me with the following error? From the console: Error: "Network Error"

Nodejs runs perfectly but when I tried to build it and run directly from the website I received this error. Network tab writes 401 response from my nextcloud. Are there any recommended steps for building the app?

Thank you all for any kind of advice.

**Comment by perry-mitchell** [comment]
Sorry for the very late reply. Unfortunately there's a couple of issues here:

 * Nextcloud famously has a few bugs with WebDAV connectivity within the browser, as they use CORS for WebDAV requests. This breaks many requests made to it from within the browser on any site besides the original domain where Nextcloud is running.
 * This library isn't readily built for the browser, yet, so it's up to the user to compile it properly using webpack or something.

This project is working fine as far as I can tell on normal WebDAV services, such as Yandex (funny example, but it's the simplest WebDAV host I've seen that's free). As such I'll close this issue. If you find a bug we can reopen, otherwise I'm afraid the debugging of your Nextcloud from within the browser is up to you.

_Side note: I'm working on releasing a browser-based copy very soon, so please test again with that once it's out._
