### ISSUE TITLE
webdav 3.6.1 Error when Array.prototype has been altered in any way

### ISSUE THREAD

**Issue by mauritslamers** [perry-mitchell/webdav-client#227]
When Array.prototype has been altered in any way, it will cause webdav 3.6.1 to fail in getting a directory contents, and possibly more. Until now I have used webdav version 1.6.1 which doesn't suffer from this issue.

I found that this is being caused by an unchecked (and therefore unsafe) for-in loop in the fast-xml-parser library which causes prototypal extensions to be parsed along with the items of a child array. 
The unsafe for-in loop can be found here: https://github.com/NaturalIntelligence/fast-xml-parser/blob/396ab96f8bd1f9953cfeff6c6b630396dd5f045a/src/node2json.js#L31

In Webdav, this bug causes file entries not to have a href value, which will result in an error "Cannot read property 'replace' of undefined at https://github.com/perry-mitchell/webdav-client/blob/5f9c061f79559db97405194c5c0d62a376f7bb2b/source/url.js#L13

I will of course also open an issue on the fast-xml-parser repository and link it here.

**Comment by perry-mitchell** [comment]
Thanks for reporting this - I'd like to make a few things clear in terms of the position of this library:

 * Prototype pollution/modification is bad and should be avoided at all costs
 * It is not the responsibility of this library to handle arrays or objects or other native types that have been modified in any way
   * That being said, I will accept PRs fixing any potential incompatibities, within reason
   * Prototype extensions should be handled correctly so that enumeration isn't possible

I'm happy to update this library when a fix has been made in fast-xml-parser.

**Comment by mauritslamers** [comment]
Thanks for responding! Let me be clear that I posted this issue here just for the sake of awareness of anyone using the webdav library. The problem originates from the use of a `for in` loop without an `Object.hasOwnProperty` check in the fast-xml-parser library, and as such the webdav library is not at fault at all.

While it is prudent to be very restrictive with prototype modifications, they sometimes are the only way to provide extra functionality with syntactical elegance in JS, that also performs well. It would be ideal if JS would allow namespacing these prototype extensions, but it seems it is either global, or nothing.

**Comment by perry-mitchell** [comment]
Closing as stale, no prio.
