### ISSUE TITLE
expose onDownloadProgress

### ISSUE THREAD

**Issue by wenerme** [perry-mitchell/webdav-client#282]
axios support onDownloadProgress, when get large file, this allowed to build a progress bar.

**Comment by wenerme** [comment]
How about when prepareRequestOptions allowed bypassing all unknown options to axios

**Comment by perry-mitchell** [comment]
> allowed bypassing all unknown options to axios

I don't want to pass just any properties to axios, as that makes this library _dependent_ on axios. I may remove axios in the future, so this dependency is something I want to avoid at all costs.

I will accept work that adds download progress, however, so that it could easily be adapted to a potential different library in the future.

**Comment by wenerme** [comment]
@perry-mitchell understand, changed the pr, also add an signal option in another pr, https://github.com/perry-mitchell/webdav-client/pull/285
