### ISSUE TITLE
client.exists throws error in console when file is not found

### ISSUE THREAD

**Issue by mtdvlpr** [perry-mitchell/webdav-client#313]
When I call the client.exists function to see if a file or directory exists I expect the 404 error that might occur to be silent and not appear inside the console.

**Comment by perry-mitchell** [comment]
Why? The console is for debugging, it is not user facing. A 404 response is a normal indicator for whether something exists at that URL or not. 

Instead of making loads of PROPFIND requests and checking directory contents, one level at a time, we can make a single call to the resource and test if it's there or not (hence the 404). The latter option is far more efficient.

I wouldn't worry about what appears in the console **network wise**.

**Comment by mtdvlpr** [comment]
Well, I get files from multiple sources, so I have to check for every file I retrieve from point A whether it exists at point B. That's a lot of errors suddenly. An error should be thrown and shown in the console when it's something that goes wrong. When you check if a recourse exists and the call returns 404 it's not going wrong and therefore there shouldn't be an error. If you want to see the result of the call, you can look in the network tab.

I would at the very least expect a parameter to make the exists function silent.

**Comment by perry-mitchell** [comment]
The logs showing the "failed" network requests is a feature of the browser, not of this library. There's nothing to silence.

If you're concerned about how the console appears, which I don't think you should be, you can perhaps use the directory contents to check every item programmatically before running other operations. If you're iterating over many files this will be more efficient anyway.

**Comment by mtdvlpr** [comment]
I see. I now also see it in your codebase. My bad. Thanks for the effort!

**Comment by perry-mitchell** [comment]
Good luck!
