### ISSUE TITLE
Error TS2709: Cannot use namespace 'HotPatcher' as a type.

### ISSUE THREAD

**Issue by pro-sumer** [perry-mitchell/webdav-client#323]
Unfortunately I (still) can't use `webdav-client` with TypeScript (due to an issue with `hot-patcher`):

```
➜ tsc
node_modules/.pnpm/webdav@4.11.0/node_modules/webdav/dist/node/compat/patcher.d.ts:2:39 - error TS2709: Cannot use namespace 'HotPatcher' as a type.

2 export declare function getPatcher(): HotPatcher;
                                        ~~~~~~~~~~


Found 1 error in node_modules/.pnpm/webdav@4.11.0/node_modules/webdav/dist/node/compat/patcher.d.ts:2
```

I did see you mention in #314 that the PR from #315 should enable using TypeScript, so I guess I'm doing something wrong?

What could that be?

Or should I wait for #317?

**Comment by blackraspberryyy** [comment]
What worked for me, instead of enabling `skipLibCheck: true`, was just adding my custom declaration file in my local project (by following this [tutorial](https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2)). Then, the contents are the same with @santiagocano08's declaration file on #315 PR. 

```
// ./src/@typings/index.d.ts

declare module "hot-patcher" {
    class HotPatcher {
        patchInline(key: string, method: any, ...args: any[]): any;
    }
    export default HotPatcher;
}

```

**Comment by perry-mitchell** [comment]
I'm looking into this now. I'm having some issues properly building `HotPatcher` for typescript.. but once that's working I'll release an update.

**Comment by perry-mitchell** [comment]
Hot Patcher and outputting non-ESM bundles has been a pain, so I've released it as an ESM module @ v2. Due to that, I'll roll it into WebDAV under a new major and will release _this_ library as ESM also.

ESM has been requested for a while, and it's definitely the way to go for new builds. So unfortunately to fix this issue it'll most likely require you to update to v5+ESM. [This](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) is good reading if you're interested in migrating to ESM.

**Comment by perry-mitchell** [comment]
Nevermind, I fixed this in another commit... I had to remove the declarations.. :sweat_smile: 

I'll still be releasing the ESM build shortly but v4 should also get this fix!

**Comment by blackraspberryyy** [comment]
I updated `webdav` to v4.11.2 on my project and `npm run build` works now without warnings or errors. 🎉🎉🎉 Thank you  @perry-mitchell!
