### ISSUE TITLE
Stat returns wrong information with folder 

### ISSUE THREAD

**Issue by ultimate-tester** [perry-mitchell/webdav-client#37]
No idea how I missed this before but when I perform a stat on a folder/directory rather than a file I will get a multistatus response containing info about all items in that folder. It should not return info about the items in the folder, it should return info about the folder itself.

This is caused because of this piece of code:

```
return fetch(url + itemPath, {
                method: "PROPFIND",
                headers: deepmerge(
                    {
                        Depth: 1
                    },
                    options.headers
                )
            })
```

To fix this, `Depth: 0` should be used instead. This has no further impact on files, because if you try to get a depth of 1 or more on a file, it will always return data as if you specified the depth to be 0. Please change to 0 or let me do a pull request with some more stat improvements.

EDIT: Looking at it some more I see that the Depth: 1 header actually causes too much data to be returned any way, there are filters in place to filter out unrequired data. This all can be prevented and skipped by `Depth: 0` as header.

**Comment by perry-mitchell** [comment]
Thanks @ultimate-tester. The depth one is required in the [directory contents listing](https://github.com/perry-mitchell/webdav-client/blob/master/source/adapter/get.js#L37), but probably not in the stat call you saw. If `0` fixes it then we can look at doing that. Please feel free to make a PR if you'd like, otherwise I can probably also help out on the weekend.
