### ISSUE TITLE
Encoding not working for folders with # in the name

### ISSUE THREAD

**Issue by nickmisasi13** [perry-mitchell/webdav-client#91]
Hi Perry,

I've been tweaking my code since your encoding additions to allow special characters. I believe I've found an issue with the way the encoding was implemented preventing the module from working with a folder with `#` in the name.

I have a folder called `/Product/test #1` and when `fetchDirContentByPath('/Product/test #1')` is run on this directory, it hits `/Products/test%20` which leads me to believe that the encoding isn't working properly.

If I try to encode the path on the way in to this module, resulting in `/Products/test%20%231` WebDAV responds with results,
![image](https://user-images.githubusercontent.com/12176405/38055348-79408d9a-32a7-11e8-85ac-0b61cb9fa712.png)
but then your `getDirectoryFiles` function fails to return any results (I get []) back from this output. I've made adjustments here f840c2c6eed653755ac804b511a2cc91aa739ec3 that I think will resolve the issue. (ignore the package.json changes, it was for testing, had issues getting it to install by git URL)

**Comment by perry-mitchell** [comment]
Sorry for the delay @nickmisasi13! Thanks for looking in to this.

The encoding issue is proving to be quite a pain. Seems like every change I make ends up revealing yet another hole in the process. I even have a [file in the tests](https://github.com/perry-mitchell/webdav-client/blob/master/test/serverContents/sub1/%E0%B8%A2%E0%B8%B2%E0%B8%81%E0%B8%88%E0%B8%99%20%231.txt) with a hash in the filename, but perhaps directories are different.

I don't have time right now to debug and try to fix this, but I'm sure it'd be easy to handle if a test were added for directories with certain characters.

**Comment by pschupp01** [comment]
Hey,
I've just posted an issue about the encoding/decoding #93 
It is not exactly similar to this one, but is related.

I just want to let you know that the test I posted on the issues 93 are also failing in your branch  f840c2c

But for different reasons.

In master:
   The directory is correctly retrieved, but the filter doesn't correctly work, and the folder appears in its children list.

In  f840c2c:
  The directory is not correctly retrieved, the getDirectoryContent match the directory which does not contains the `%20`(it matches `two words` instead of `two%20words`
