### ISSUE TITLE
Name decoding is broken for already encoded characters.

### ISSUE THREAD

**Issue by pschupp01** [perry-mitchell/webdav-client#93]
I was facing this issue today, and managed to implement a simple failing test.

If a directory has a name containing encoded character it will fail to get the correct directory name.

I have added a directory with name `two%20words`, containing a single file.
And testing `getDirectoryContents` on this folder.

Step to reproduce:
• Add `./test/serverContents/two%20words/file2.txt`
• Add the following test in `getDirectoryContents.spec.js`
   ```
      it("returns only the directory content when encoded special characters in name", function() {
        return this.client.getDirectoryContents("/two%20words").then(function(contents) {
            console.log(contents);
            expect(contents).to.have.lengthOf(1);
            expect(contents[0].basename).to.equal("file2.txt");
        });
    });
   ```
• npm t

**Comment by perry-mitchell** [comment]
Thanks @pschupp01! This helps alot :)

**Comment by perry-mitchell** [comment]
Added the failing test here: https://github.com/perry-mitchell/webdav-client/pull/94

Will try to address both this and #91

**Comment by perry-mitchell** [comment]
It's weird though, because it requests the correct URL: `http://localhost:9988/webdav/server/two%2520words`, but the result is wrong. The result should contain contents that include `file2.txt`, but instead I get `http://localhost:9988/webdav/server/two%20words/file.txt` in the response.. Looks like the server might be treating this incorrectly as well.

**Comment by perry-mitchell** [comment]
It looks like the decoding done on the filenames when the response is received is breaking the process.
